import 'package:monks_helper/app/model/mantra.dart';
import '../app/model/rgb.dart';

class MockData {
  static List<Mantra> mantraList = [
    Mantra(
      id: 1,
      name: 'Mantra 1',
      buddhaName: 'Buda 1',
      symbol: 'lib\\assets\\images\\buddhaMeditation.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 100,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 0, g: 2018, b: 7),
    ),
    Mantra(
      id: 2,
      name: 'Mantra 2',
      buddhaName: 'Buda 2',
      symbol: 'lib\\assets\\images\\dharma-wheel.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 100,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 255, g: 3, b: 3),
    ),
    Mantra(
      id: 3,
      name: 'Mantra 3',
      buddhaName: 'Buda 3',
      symbol: 'lib\\assets\\images\\jewel.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 100,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 236, g: 255, b: 3),
    ),
    Mantra(
      id: 4,
      name: 'Mantra 4',
      buddhaName: 'Buda 4',
      symbol: 'lib\\assets\\images\\vajra.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 100,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 3, g: 3, b: 255),
    ),
    Mantra(
      id: 5,
      name: 'Mantra 5',
      buddhaName: 'Buda 5',
      symbol: 'lib\\assets\\images\\lotus.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 10000,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 255, g: 255, b: 255),
    ),
    Mantra(
      id: 6,
      name: 'Mantra 6',
      buddhaName: 'Buda 6',
      symbol: 'lib\\assets\\images\\doubleVajra.png',
      mantraDesc: 'AOM',
      qtdR: 10,
      goal: 10000,
      acc: 0,
      percentBar: 0,
      percentValue: 0,
      rgb: Rgb(r: 212, g: 0, b: 254),
    ),
  ];
}
